swiss_macro_monitor:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: swiss-macro-monitor
      dataset: swiss_macro
      keyfile: /tmp/gcp_key.json
      threads: 4
      timeout_seconds: 300
      location: EU
